engineStrict: true

ignoreScripts: true

lockfile: true

minimumReleaseAge: 10080

nodeVersion: 24.11.1

overrides:
  esbuild@<=0.24.2: '>=0.25.0'

preferFrozenLockfile: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver
