CREATE TABLE IF_FKONTO_12
(
    IF01_KODE        CHAR(1)        NULL,
    IF01_AGNR_FNR    NUMERIC(11, 0) NULL,
    IF10_FORSFOM_SEQ NUMERIC(8, 0)  NULL,
    IF12_BETDATO_SEQ NUMERIC(8, 0)  NULL,
    IF12_FOM         NUMERIC(8, 0)  NULL,
    IF12_TOM         NUMERIC(8, 0)  NULL,
    IF12_BET_KODE    CHAR(1)        NULL,
    IF12_FRIUKER     CHAR(2)        NULL,
    IF12_BELOEP      NUMERIC(7, 2)  NULL,
    IF12_BETDATO     NUMERIC(8, 0)  NULL,
    OPPRETTET        TIMESTAMP(6)   NOT NULL,
    ENDRET_I_KILDE   TIMESTAMP(6)   NOT NULL,
    KILDE_IF         VARCHAR(12)    NOT NULL,
    ID_KONT          NUMERIC        NOT NULL,
    OPPDATERT        TIMESTAMP(6)   NULL
)
