ALTER TABLE IF_VEDFRIVT_10
    ADD CONSTRAINT IF_VEDFRIVT_10_PK PRIMARY KEY (ID_VED);

ALTER TABLE IF_FKONTO_12
    ADD CONSTRAINT IF_FKONTO_12_PK PRIMARY KEY (ID_KONT);

CREATE SEQUENCE ID_VED_SEQ START WITH 1;

CREATE SEQUENCE ID_KONT_SEQ START WITH 1;
