[versions]
flyway = "13.3.0"
ktor = "3.6.0"
nodeGradle = "7.1.0"
sykepengerGradlePlugins = "20261001.1830"
tbdLibs = "2026.01.22-09.16-1d3f6039"
testcontainers = "2.0.5"

[libraries]
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-databasePostgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hikaricp = "com.zaxxer:HikariCP:7.1.0"
kotliquery = "com.github.seratch:kotliquery:1.9.1"
postgresql = "org.postgresql:postgresql:42.7.13"

ktor-client-auth = { module = "io.ktor:ktor-client-auth-jvm", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-jackson = { module = "io.ktor:ktor-client-jackson", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json-jvm", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock-jvm", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }

mockk = "io.mockk:mockk:1.13.9"
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }

rapidsAndRivers = "com.github.navikt:rapids-and-rivers:2026011411051768385145.e8ebad1177b4"

tbdLibs-azureTokenClientDefault = { module = "com.github.navikt.tbd-libs:azure-token-client-default", version.ref = "tbdLibs" }
tbdLibs-naisfulApp = { module = "com.github.navikt.tbd-libs:naisful-app", version.ref = "tbdLibs" }
tbdLibs-naisfulTestApp = { module = "com.github.navikt.tbd-libs:naisful-test-app", version.ref = "tbdLibs" }
tbdLibs-rapidsAndRiversTest = { module = "com.github.navikt.tbd-libs:rapids-and-rivers-test", version.ref = "tbdLibs" }
tbdLibs-speedClient = { module = "com.github.navikt.tbd-libs:speed-client", version.ref = "tbdLibs" }

[bundles]
ktor-client = [
    "ktor-client-auth",
    "ktor-client-cio",
    "ktor-client-contentNegotiation",
    "ktor-client-jackson",
    "ktor-client-json",
    "ktor-websockets"
]

[plugins]
nodeGradle = { id = "com.github.node-gradle.node", version.ref = "nodeGradle" }
sykepenger-deployable = { id = "no.nav.sykepenger.deployable", version.ref = "sykepengerGradlePlugins" }
