apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis-testdata
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 10
  readiness:
    path: /isready
    initialDelay: 10
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
  ingresses:
    - https://spleis-testdata.intern.dev.nav.no
    - https://spleis-testdata.ansatt.dev.nav.no
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      external:
        - host: team-inntekt-proxy.dev-fss-pub.nais.io
        - host: aareg-services-q2.dev-fss-pub.nais.io
        - host: ereg-services-q2.dev-fss-pub.nais.io
      rules:
        - application: logging
          namespace: nais-system
        - application: speed-api
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spleis-testdata-v1
    - name: INNTEKTSKOMPONENTEN_URL
      value: https://team-inntekt-proxy.dev-fss-pub.nais.io/proxy/inntektskomponenten-q2/rs
    - name: INNTEKTSKOMPONENTEN_SCOPE
      value: api://dev-fss.team-inntekt.inntektskomponenten/.default
    - name: AAREG_URL
      value: https://aareg-services-q2.dev-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: api://dev-fss.arbeidsforhold.aareg-services-nais/.default
    - name: EREG_BASE_URL
      value: https://ereg-services-q2.dev-fss-pub.nais.io
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
