apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: tbd
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 30
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
  ingresses:
    - https://spleis-testdata.intern.dev.nav.no
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      external:
       - host: team-inntekt-proxy.dev-fss-pub.nais.io
       - host: aareg-services-q1.dev-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spleis-testdata-v1
    - name: INNTEKTSKOMPONENTEN_URL
      value: https://team-inntekt-proxy.dev-fss-pub.nais.io/proxy/inntektskomponenten-q1/rs
    - name: INNTEKTSKOMPONENTEN_RESOURCE_ID
      value: dev-fss.team-inntekt.inntektskomponenten
    - name: AAREG_URL
      value: https://aareg-services-q1.dev-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: api://dev-fss.arbeidsforhold.aareg-services-nais-q1/.default
