apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: tbd
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 30
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  ingresses:
    - https://spleis-testdata.nais.preprod.local
    - https://spleis-testdata.dev-fss.nais.io
    - https://spleis-testdata.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvspleistestdata
  env:
    - name: DATABASE_HOST_SPLEIS
      value: b27dbvl008.preprod.local
    - name: DATABASE_PORT_SPLEIS
      value: "5432"
    - name: DATABASE_NAME_SPLEIS
      value: spleis
    - name: DATABASE_HOST_SPESIALIST
      value: b27dbvl009.preprod.local
    - name: DATABASE_PORT_SPESIALIST
      value: "5432"
    - name: DATABASE_NAME_SPESIALIST
      value: spesialist
    - name: DATABASE_HOST_SPENN
      value: b27dbvl007.preprod.local
    - name: DATABASE_PORT_SPENN
      value: "5432"
    - name: DATABASE_NAME_SPENN
      value: helse-spenn-oppdrag
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spleis-testdata-v1
