apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
  readiness:
    path: /is_ready
    initialDelay: 5
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  ingresses:
    - https://spleis-testdata.nais.preprod.local
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /serviceuser/data/dev/srvspleistestdata
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: DATABASE_HOST
      value: b27dbvl008.preprod.local
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: spleis
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
