CREATE TABLE OPPDRAG
(
    AVSTEMMINGSNOKKEL BIGINT NOT NULL PRIMARY KEY,
    SJEKKSUM INTEGER NOT NULL,
    FAGOMRADE VARCHAR(32) NOT NULL,
    FNR VARCHAR(32) NOT NULL,
    MOTTAKER VARCHAR(32) NOT NULL,
    OPPRETTET TIMESTAMP NOT NULL,
    ENDRET TIMESTAMP,
    FAGSYSTEM_ID VARCHAR(32) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    AVSTEMT BOOLEAN DEFAULT FALSE NOT NULL,
    TOTALBELOP INTEGER NOT NULL,
    BESKRIVELSE TEXT,
    FEILKODE_OPPDRAG VARCHAR(32) DEFAULT NULL,
    BEHOV JSON,
    OPPDRAG_RESPONSE TEXT,
    ORGNR VARCHAR(32) NOT NULL
);
